### ISSUE TITLE
Wrong View got activated when another overlapped view is clicked

### ISSUE THREAD

**Issue by angelkoh** [Quatja/Vorolay#4]
I set up a clickListener for the views in the vorolay layout. When I click a region on an imageView that's "overlapped" by another, the other imageView is activated (see attached image).

is there any settings I can configure?

the following are my codes 
 
        for (int i = 0; i < count; i++) {
            RelativeLayout rl = (RelativeLayout) layoutInflater.inflate(R.layout.item_voronoi, null, false);

            ImageView iv = ( ImageView) rl.findViewById(R.id.image);

           //add a callback when the image is clicked
            int value = i;
            iv.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    Log.d("TEST", "item clicked: "+ value);
                }
            }); 

            loadImage(iv, uri);  //this method populates the image

            vv.addView(rl); //this is the VoronoiView
        }  

![touchdetect](https://cloud.githubusercontent.com/assets/829758/22723320/42e199f0-edf8-11e6-8968-260af81766bf.png)

**Comment by Firtzberg** [comment]
I think you should use an [OnRegionClickListener](https://github.com/Quatja/Vorolay/blob/master/vorolay/src/main/java/quatja/com/vorolay/VoronoiView.java#L89) instead. I have not tried it.
The implementation could really be improved by actually invoking the onTouchEvent() of the child rather than inventing a new listener.
